### ISSUE TITLE
feat: formulas with relations

### ISSUE THREAD

**Issue by bbtgnn** [bbtgnn/motion#22]
### Scenario

Imagine I have three collections
- regions
- sub-regions
- houses

let's say that
- regions have sub-regions
- sub-regions have houses

Say that I want to calculate all the houses in the regions
- I create a `formula` property on `regions`
- I write: `this.subregions.houses` ( -> the final type of the "formula" field is `houses`)

---

### ToDo

Needed to achieve this:
- [ ] feat: formula property

Next features:
- [ ] feat(formulas): autocomplete on dot notation
- [ ] feat(formulas): add filters
